git:
  depth: 1

matrix:
  include:
     - name: "algorithms, tests -- linux, debug, cppcheck, coverage, g++, 64-bit"
       os: linux
       dist: xenial
       language: cpp
       env: BUILD_TYPE="Debug"
       compiler: g++
       sudo: required
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-6
             - cppcheck
             - valgrind
       install: export CXX="g++-6"
       script:
         - set -e

         - cppcheck --enable=all -I include --language=c++ --platform=unix64 --std=c++11 --check-config --suppress=missingIncludeSystem
                    -v src

         - cmake -Bbuild -H. -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -DCOVERAGE:BOOL=ON
         - cmake --build build --target algorithms --config $BUILD_TYPE -- -j $(nproc)

         - cmake -Bbuild/submodules/test-utils -Hsubmodules/test-utils -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE

         - cmake -Bbuild/tests/unit -Htests/unit
                 -Dalgorithms_DIR:PATH=$(pwd)/build
                 -Dtest-utils_DIR:PATH=$(pwd)/build/submodules/test-utils
                 -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
         - cmake --build build/tests/unit --target run-all-tests-verbose --config $BUILD_TYPE -- -j $(nproc)

         - bash <(curl -s https://codecov.io/bash)

         - valgrind --error-exitcode=255 -v build/tests/unit/tests

         - set +e

     - name: "function-loader, example, tests -- osx, release with debug info, valgrind, clang++, 64-bit"
       os: osx
       osx_image: xcode10.1
       language: cpp
       env: BUILD_TYPE="Release"
       compiler: clang
       script:
         - set -e

         - cmake -Bbuild -H. -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
         - cmake --build build --target algorithms --config $BUILD_TYPE -- -j $(sysctl -n hw.ncpu)

         - cmake -Bbuild/submodules/test-utils -Hsubmodules/test-utils -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE

         - cmake -Bbuild/tests/unit -Htests/unit
                 -Dalgorithms_DIR:PATH=$(pwd)/build
                 -Dtest-utils_DIR:PATH=$(pwd)/build/submodules/test-utils
                 -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
         - cmake --build build/tests/unit --target run-all-tests-verbose --config $BUILD_TYPE -- -j $(sysctl -n hw.ncpu)

         - set +e
